language: python
python: 2.7
git:
  depth: 3
sudo: false
env:
  global:
  - PYTHON="python"
  - PIP_INSTALL="pip install"
  - BUILD_CMD=
  matrix:
  - TRAVIS_4681_WORKAROUND=1
matrix:
  include:
  - os: osx
    osx_image: xcode9.1
    language: generic
    env:
    - PYTHON="python3"
    - TOXENV=py3
    - PIP_INSTALL="pip install --user"
    - BUILD_CMD="python3 setup.py bdist_wheel"
  - os: osx
    osx_image: xcode9.1
    language: generic
    env:
    - PYTHON=python2""
    - TOXENV=py27
    - PIP_INSTALL="pip install --user"
    - BUILD_CMD="python2 setup.py bdist_wheel"
  - os: linux
    env: TOXENV=py27
    python: 2.7
  - os: linux
    env: TOXENV=py34
    python: 3.4
  - os: linux
    env: TOXENV=py35
    python: 3.5
  - os: linux
    env: TOXENV=py36
    python: 3.6
# strange random hang error on pypy that is difficult to reproduce.
# Disable test for now.
#  - os: linux
#    env: TOXENV=pypy
#    python: pypy
  - os: linux
    env: TOXENV=pypy3
    python: pypy3
  - os: linux
    env: TOXENV=docs
# create linux binary manylinux builds, see tools/manylinux-build
  - sudo: required
    services:
      - docker
    env:
    - TOXENV=manylinux
    - GITHUB_UPLOAD=yes
  exclude:
  - env: TRAVIS_4681_WORKAROUND=1
before_install:
- chmod ugo+x .travis_before_install.sh
- "./.travis_before_install.sh"
install:
- echo $PATH
- which $PYTHON
- "travis_retry $PYTHON -m $PIP_INSTALL virtualenv tox wheel"
script:
- $PYTHON -m tox
- $BUILD_CMD
deploy:
  provider: bintray
  file: "bintray.json"
  user: "viblo"
  key:
    secure: A1i4M85KqB5/wp9MB/6U6JK2Np1x2hzY4lhIUXpgxlP6pqNUl35AGp3uakWV9YMubc00qeWMou+/+5yEuRK87ON0LKSJ6BqQoxIaNxiTxvqXn86Pw8ASl+7eU/SB4dDSDfA6Cc6eSZKo+dXMLHL+kSq06Ojumz1ok6tbpiCwrOQ=
  dry-run: true
  on: "bintray-osx"
