environment:
  matrix:
    - PYTHON: "C:\\Python36"
      MINGW: "mingw32"
    - PYTHON: "C:\\Python36-x64"
      MINGW: "mingw64"
    - PYTHON: "C:\\Python37"
      MINGW: "mingw32"
    - PYTHON: "C:\\Python37-x64"
      MINGW: "mingw64"

#platform:
#  - x86
  #- x64

#matrix:
#  fast_finish: true

clone_depth: 3

init:
  - ECHO %PYTHON%

install:
  # tox for testing
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -m pip install tox"
  # We need wheel installed to build wheels
  - "python -m pip install --upgrade wheel"
  
build_script: 
  - python setup.py bdist_wheel

test_script:
  # get the wheel file and use it as input to tox
  - python -c "import glob,tox;tox.cmdline(['-e', 'py', '-vv', '--installpkg', glob.glob('dist/*.whl')[0]])"

artifacts:
  - path: dist\*
